# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-12 15:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grads', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='graduate',
            options={},
        ),
        migrations.AddField(
            model_name='graduate',
            name='first_name',
            field=models.CharField(default='Iron', max_length=300),
        ),
        migrations.AddField(
            model_name='graduate',
            name='job_title',
            field=models.CharField(default='Web Developer', max_length=300),
        ),
        migrations.AddField(
            model_name='graduate',
            name='last_name',
            field=models.CharField(default='Yard', max_length=300),
        ),
        migrations.AlterField(
            model_name='graduate',
            name='Email',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='graduate',
            name='Github',
            field=models.URLField(blank=True, max_length=600),
        ),
        migrations.AlterField(
            model_name='graduate',
            name='Linkedin',
            field=models.URLField(blank=True, max_length=600),
        ),
        migrations.AlterField(
            model_name='graduate',
            name='Picture',
            field=models.ImageField(blank=True, upload_to='portait/'),
        ),
        migrations.RemoveField(
            model_name='graduate',
            name='Name',
        ),
        migrations.AlterOrderWithRespectTo(
            name='graduate',
            order_with_respect_to='first_name',
        ),
    ]
