# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-21 16:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grads', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Graduate',
            new_name='Graduates',
        ),
    ]
