# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-25 20:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grads', '0002_auto_20170421_1648'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='graduates',
            options={'ordering': ['first_name'], 'verbose_name': []},
        ),
        migrations.RemoveField(
            model_name='graduates',
            name='Name',
        ),
        migrations.AddField(
            model_name='graduates',
            name='first_name',
            field=models.CharField(default='Iron', max_length=300),
        ),
        migrations.AddField(
            model_name='graduates',
            name='last_name',
            field=models.CharField(default='Yard', max_length=300),
        ),
        migrations.AlterField(
            model_name='graduates',
            name='Email',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='graduates',
            name='Github',
            field=models.URLField(blank=True, max_length=600),
        ),
        migrations.AlterField(
            model_name='graduates',
            name='Linkedin',
            field=models.URLField(blank=True, max_length=600),
        ),
        migrations.AlterField(
            model_name='graduates',
            name='Picture',
            field=models.ImageField(blank=True, upload_to='media/portait/'),
        ),
    ]
