# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-25 20:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grads', '0004_auto_20170425_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graduates',
            name='Picture',
            field=models.ImageField(blank=True, upload_to='/portait/'),
        ),
    ]
