# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-25 21:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grads', '0008_auto_20170425_1710'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='graduates',
            options={},
        ),
        migrations.AlterOrderWithRespectTo(
            name='graduates',
            order_with_respect_to='first_name',
        ),
    ]
