# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-25 21:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grads', '0009_auto_20170425_1721'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Graduates',
            new_name='Graduate',
        ),
    ]
