# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-21 16:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Graduate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=2000)),
                ('Email', models.CharField(max_length=3000)),
                ('Github', models.URLField(blank=True, max_length=2000)),
                ('Linkedin', models.URLField(blank=True, max_length=2000)),
                ('Picture', models.ImageField(blank=True, upload_to='/media/')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['Name'],
            },
        ),
    ]
