# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-10 17:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Graduate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('first_name', models.CharField(default='Iron', max_length=300)),
                ('last_name', models.CharField(default='Yard', max_length=300)),
                ('job_title', models.CharField(default='Web Developer', max_length=300)),
                ('Email', models.CharField(max_length=1000)),
                ('Github', models.URLField(blank=True, max_length=600)),
                ('Linkedin', models.URLField(blank=True, max_length=600)),
                ('Picture', models.ImageField(blank=True, upload_to='portait/')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='details', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['first_name'],
            },
        ),
    ]
