# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-12 15:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('grads', '0002_auto_20170612_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='graduate',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='details', to=settings.AUTH_USER_MODEL),
        ),
    ]
