# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-27 20:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grads', '0004_auto_20170613_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='graduate',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
